---
- name: YUM-Based | Install rke2-agent
  yum:
    name: rke2-agent
    state: latest  # noqa package-latest
  when: ansible_os_family == 'RedHat'

- name: TARBALL | Moving Systemd units to /etc/systemd/system
  ansible.builtin.copy:
    src: /usr/local/lib/systemd/system/rke2-agent.service
    dest: /etc/systemd/system/rke2-agent.service
    mode: '0755'
    owner: root
    group: root
    remote_src: yes
  when: ansible_os_family != 'RedHat'

- name: Add server url to config file
  lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: "server: https://{{ server_ip }}:9345"

- name: Add token to config.yaml
  lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: "token: {{ hostvars['RKE2_TOKEN_HOLDER']['token'] }}"

- name: Start rke2-agent
  ansible.builtin.systemd:
    name: rke2-agent
    state: started
    enabled: yes
