---
- name: YUM | Install rke2-agent
  yum:
    name: rke2-agent
    state: latest  # noqa package-latest

- name: config.yaml | server
  lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: "server: https://{{ server_ip }}:9345"

- name: SYSTEMD | rke2-agent
  ansible.builtin.systemd:
    name: rke2-agent
    state: started
    enabled: yes
