---
- name: Install rke2-agent
  yum:
    name: rke2-agent
    state: latest  # noqa package-latest

- name: Add server url to config file
  lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: "server: https://{{ server_ip }}:9345"

- name: Add token to config.yaml
  lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: "token: {{ hostvars['RKE2_TOKEN_HOLDER']['token'] }}"

- name: Start rke2-agent
  ansible.builtin.systemd:
    name: rke2-agent
    state: started
    enabled: yes
