---

- hosts: rke2_cluster
  gather_facts: yes
  become: yes
  roles:
    - role: prereqs

- hosts: server[0]
  become: yes
  roles:
    - role: first_server

- hosts: server[1:]
  become: yes
  roles:
    - role: server

- hosts: agent
  become: yes
  roles:
    - role: agent

# - hosts: rke2_cluster
#   gather_facts: yes
#   become: yes
#   roles:
#     - role: hardening
