---

- hosts: rke2_cluster
  roles:
    - role: common/init
      become: true

- name: Server play
  hosts: rke2_servers
  any_errors_fatal: true
  become: true
  roles:
    - role: rke2_server
  serial: 1
  vars_files:
    - inventory/skaro/group_vars/vault.yaml

- name: Agent play
  hosts: rke2_agents
  any_errors_fatal: true
  become: true
  roles:
    - role: rke2_agent
  serial: 3

- name: Cluster manifest play
  hosts: rke2_servers
  any_errors_fatal: true
  become: true
  roles:
    - role: cluster_manifest

# - hosts: rke2_servers
#   vars_files:
#     - inventory/skaro/group_vars/vault.yaml
#   roles:
#     - role: k8s/secrets
#       become: true

# - hosts: localhost
#   vars_files:
#     - inventory/skaro/group_vars/vault.yaml
#   roles:
#     - role: k8s/charts
#       become: false