---
# /etc/rancher/rke2/config.yaml`
- name: create the /etc/rancher/rke2 config dir
  ansible.builtin.file:
    path: /etc/rancher/rke2
    state: directory
    recurse: yes

- name: create the /etc/rancher/rke2/config.yaml file
  ansible.builtin.file:
    path: /etc/rancher/rke2/config.yaml
    state: touch

- name: create the /etc/rancher/rke2 config dir
  ansible.builtin.file:
    path: /etc/rancher/rke2
    state: directory
    recurse: yes

- name: create the airgap images folder
  ansible.builtin.file:
    path: /var/lib/rancher/rke2/agent/images
    state: directory
    recurse: yes

- name: create the /etc/rancher/rke2/config.yaml file
  ansible.builtin.file:
    path: /etc/rancher/rke2/config.yaml
    state: touch

# CONFIG FILE GENERATION
- name: rke2- config enable selinux
  lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: "selinux: {{ rke2_selinux }}"

- name: rke2- write-kubeconfig-mode
  lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: "write-kubeconfig-mode: {{ rke2_write_kubeconfig_mode }}"
