---

- import_tasks: yum.yml

- import_tasks: master-config.yml
  when: role == "init_master"

- import_tasks: agent-config.yml
  when: role == "master"

- import_tasks: agent-config.yml
  when: role == "agent"

# Firewalld | disable
- name: FIREWALLD | disable
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: no

# CIS mode
- import_tasks: cis-profile.yml
  when: rke2_cis_mode

#need to add when role==master
- include_tasks: rke2-master.yml
  when: role == "init_master" 

- include_tasks: rke2-master-additions.yml
  when: role == "master" 

- include_tasks: rke2-agent.yml
  when: role =="agent"

- import_tasks: kubectl-install.yml
  when: role == "init_master"

- import_tasks: kubectl-install.yml
  when: role == "init_master"

- import_tasks: kubectl-config.yml
  when: role == "init_master"
