---
- name: YUM-Based | Install rke2-server
  yum:
    name: rke2-server
    state: latest  # noqa package-latest
  when:
    - ansible_facts['os_family'] == 'RedHat'
    - not got_rke2_install_ball.stat.exists

- name: TARBALL | Moving Systemd units to /etc/systemd/system
  ansible.builtin.copy:
    src: /usr/local/lib/systemd/system/rke2-server.service
    dest: /etc/systemd/system/rke2-server.service
    mode: '0644'
    owner: root
    group: root
    remote_src: yes
  when:
    - ansible_facts['os_family'] != 'RedHat' or got_rke2_install_ball.stat.exists

- name: Add write-kubeconfig-mode to config.yaml
  lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: "write-kubeconfig-mode: {{ rke2_write_kubeconfig_mode }}"
  when: rke2_write_kubeconfig_mode is defined

- name: Add tls-san to first server pt1
  lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: "tls-san:"
  when: tls_san is defined

- name: Add tls-san to first server pt2
  lineinfile:
    path: /etc/rancher/rke2/config.yaml
    insertafter: "tls-san:"
    line: "  - {{ item }}"
  with_items:
    - "{{ tls_san }}"
  when: tls_san is defined

- name: Start rke2-server
  ansible.builtin.systemd:
    name: rke2-server
    state: started
    enabled: yes

- name: Add user provided Token to config.yml if given
  lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: "token: {{ rke2_config_token }}"
  when: rke2_config_token | length > 0

- name: Add generated Token if none provided
  when: rke2_config_token | length == 0
  block:
    - name: Wait for node-token
      wait_for:
        path: /var/lib/rancher/rke2/server/node-token

    - name: Read node-token from master
      slurp:
        src: /var/lib/rancher/rke2/server/node-token
      register: node_token

    - name: Store Master node-token
      set_fact:
        rke2_config_token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"
