---

- name: Add server url to config file
  lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: "server: https://{{ kubernetes_api_server_host }}:9345"

- name: Add token to config.yaml
  lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: "token: {{ hostvars[groups['rke2_servers'][0]].rke2_config_token }}"

- name: Start and wait for healthy node
  throttle: 1
  block:
    - name: Start rke2-server
      ansible.builtin.systemd:
        name: rke2-server
        state: started
        enabled: yes

    - name: Wait for k8s apiserver reachability
      wait_for:
        host: "{{ kubernetes_api_server_host }}"
        port: "6443"
        state: present
        timeout: 300

    - name: Wait for node to show Ready status
      ansible.builtin.shell: >-
        /var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml
        --server https://127.0.0.1:6443 get no {{ inventory_hostname }}
        -o jsonpath='{.status.conditions[?(@.type=="Ready")].status}'
      register: status_result
      until: status_result.stdout.find("True") != -1
      retries: 20
      delay: 10
      changed_when: false
