---

- name: Add manifest addons files
  ansible.builtin.copy:
    src: "{{ manifest_config_file_path }}"
    dest: "{{ rke2_data_dir }}/server/manifests/"
    mode: '0640'
    owner: root
    group: root
