---
- name: Air-Gap Images
  become: yes
  when: got_images_gz.stat.exists == true or got_images_zst.stat.exists == true
  block:
    - name: Does the airgap images folder exist?
      stat:
        path: /var/lib/rancher/rke2/agent/images
      register: rke2_agent_images

    - name: create the airgap images folder
      file:
        path: /var/lib/rancher/rke2/agent/images
        state: directory
        recurse: yes
      when: not rke2_agent_images.stat.exists

    - name: Add images tar.gz to needed directory if provided
      copy:
        src: "{{ playbook_dir }}/tarball_install/rke2-images.linux-amd64.tar.gz"
        dest: /var/lib/rancher/rke2/agent/images/
        mode: '0644'
      when: got_images_gz.stat.exists == true

    - name: Add images tar.zst to needed directory if provided
      copy:
        src: "{{ playbook_dir }}/tarball_install/rke2-images.linux-amd64.tar.zst"
        dest: /var/lib/rancher/rke2/agent/images/
        mode: '0644'
      when: got_images_zst.stat.exists == true

- name: Air-Gap Tarball Install
  become: yes
  when: got_rke2_install_ball.stat.exists == true
  block:
    - name: TARBALL | Make temp dir
      ansible.builtin.tempfile:
        state: directory
        suffix: rke2-install.XXXXXXXXXX
      register: temp_dir

    - name: Add tarball to needed directory if provided
      copy:
        src: "{{ playbook_dir }}/tarball_install/rke2.linux-amd64.tar.gz"
        dest: "{{ temp_dir.path }}/rke2.linux-amd64.tar.gz"
        mode: '0644'

    - name: TARBALL | Extract the tarball  # noqa command-instead-of-module
      command:
        cmd: tar -xf "{{ temp_dir.path }}/rke2.linux-amd64.tar.gz" -C "{{ tarball_dir }}"
      changed_when: false

    - name: TARBALL | Remove the temp_dir
      ansible.builtin.file:
        path: "{{ temp_dir.path }}"
        state: absent
      when: temp_dir.path is defined
