---
- name: CIS MODE
  block:
    - name: Enable CIS-MODE 1.5
      ansible.builtin.lineinfile:
        dest: /etc/rancher/rke2/config.yaml
        line: "profile: cis-1.5"

    # create etcd group
    - name: Create etcd group
      ansible.builtin.group:
        name: etcd
        state: present

    # create etcd user
    - name: Create etcd user
      ansible.builtin.user:
        name: etcd
        comment: etcd user
        shell: /bin/nologin
        group: etcd

    - name: Copy systemctl file for kernel hardening
      ansible.builtin.copy:
        src: /usr/share/rke2/rke2-cis-sysctl.conf
        dest: /etc/sysctl.d/60-rke2-cis.conf
        remote_src: yes
      notify:
        - restart systemd-sysctl
  become: yes
  when: cis_15_enabled | bool == true
