---
- name: CIS MODE
  become: yes
  when: rke2_config.profile | default("") | string == "cis-1.5"
  block:
    - name: Enable CIS-MODE 1.5
      ansible.builtin.lineinfile:
        dest: /etc/rancher/rke2/config.yaml
        line: "profile: cis-1.5"

    # create etcd group
    - name: Create etcd group
      ansible.builtin.group:
        name: etcd
        state: present

    # create etcd user
    - name: Create etcd user
      ansible.builtin.user:
        name: etcd
        comment: etcd user
        shell: /bin/nologin
        group: etcd

    - name: Copy systemctl file for kernel hardening for yum installs
      ansible.builtin.copy:
        src: /usr/share/rke2/rke2-cis-sysctl.conf
        dest: /etc/sysctl.d/60-rke2-cis.conf
        remote_src: yes
      register: sysctl_operation_yum
      when:
        - ansible_os_family == 'RedHat'
        - not got_rke2_install_ball.stat.exists

    - name: Copy systemctl file for kernel hardening for non-yum installs
      ansible.builtin.copy:
        src: /usr/local/share/rke2/rke2-cis-sysctl.conf
        dest: /etc/sysctl.d/60-rke2-cis.conf
        remote_src: yes
      register: sysctl_operation_tarball
      when: ansible_facts['os_family'] != 'RedHat' or got_rke2_install_ball.stat.exists

    - debug: msg={{ sysctl_operation_yum }}
    - debug: msg={{ sysctl_operation_tarball }}

    - name: restart systemd-sysctl
      service:
        state: restarted
        name: systemd-sysctl
      when: sysctl_operation_yum.changed or sysctl_operation_tarball.changed

    - pause:

    - name: Reboot the machine (Wait for 5 min)
      reboot:
        reboot_timeout: 300
      when: sysctl_operation_yum.changed or sysctl_operation_tarball.changed
