---

- name: Create the /etc/rancher/rke2 config dir
  ansible.builtin.file:
    path: /etc/rancher/rke2
    state: directory
    recurse: yes

- name: create the /etc/rancher/rke2/config.yaml file
  ansible.builtin.file:
    path: /etc/rancher/rke2/config.yaml
    state: touch
    mode: "0640"
    owner: root
    group: root

- name: Set a fact
  ansible.builtin.set_fact:
    all_node_labels: "{{ rke2_config['node-label'] | default([]) }} + {{ extra_node_labels | default([]) }}"

- name: Add node labels to rke2_config
  ansible.utils.update_fact:
    updates:
      - path: rke2_config["node-label"]
        value: "{{ all_node_labels }}"
  register: updated_rke2_config

- name: Add primary configuration items
  copy:
    content: "{{ updated_rke2_config.rke2_config | to_nice_yaml(indent=0) }}"
    dest: /etc/rancher/rke2/config.yaml
    mode: "0640"
    owner: root
    group: root
