---
- name: Does the /etc/rancher/rke2 dir exist?
  stat:
    path: /etc/rancher/rke2
  register: rke2_directory

- name: Create the /etc/rancher/rke2 config dir
  file:
    path: /etc/rancher/rke2
    state: directory
    recurse: yes
  when: not rke2_directory.stat.exists

- name: Does the /etc/rancher/rke2/config.yaml file exist?
  stat:
    path: /etc/rancher/rke2/config.yaml
  register: previous_rke2_config

- name: Read previous_rke2_config
  slurp:
    src: /etc/rancher/rke2/config.yaml
  register: full_orig_rke2_config
  when: previous_rke2_config.stat.exists

- name: Decode contents of slurp
  set_fact:
    orig_rke2_config: "{{ full_orig_rke2_config['content'] | b64decode }}"
  when: previous_rke2_config.stat.exists

- name: Get rke2_config node-labels/taints and host var node-labels/taints
  set_fact:
    rke2_config_node_labels: "{{ rke2_config['node-label'] | default([]) }}"
    rke2_config_node_taints: "{{ rke2_config['node-taint'] | default([]) }}"
    host_var_node_labels: "{{ node_labels | default([]) }}"
    host_var_node_taints: "{{ node_taints | default([]) }}"
  changed_when: false

- name: Combine rke2_config node-labels/taints and hostvar node-labels/taints
  set_fact:
    all_node_labels: "{{ rke2_config_node_labels + host_var_node_labels }}"
    all_node_taints: "{{ rke2_config_node_taints + host_var_node_taints }}"
  changed_when: false

- name: Template a temporary config file
  ansible.builtin.template:
    src: config.yml.j2
    dest: /tmp/ansible-config.txt
    mode: '0600'
    owner: root
    group: root
  changed_when: false

- name: Get original token
  set_fact:
    original_token: "{{ orig_rke2_config | regex_search('token: (.+)') }}"
  when: previous_rke2_config.stat.exists
  changed_when: false

- name: Add token to config.yaml
  lineinfile:
    dest: /tmp/ansible-config.txt
    line: "{{ original_token }}"
    state: present
    insertbefore: BOF
  when: previous_rke2_config.stat.exists and original_token | length > 0
  changed_when: false

- name: Get original server
  set_fact:
    original_server: "{{ orig_rke2_config | regex_search('server: https://(.*):9345') }}"
  when: previous_rke2_config.stat.exists
  changed_when: false

- name: Add server url to config file
  lineinfile:
    dest: /tmp/ansible-config.txt
    line: "{{ original_server }}"
    state: present
    insertbefore: BOF
  when: previous_rke2_config.stat.exists and original_server | length > 0
  changed_when: false

- name: Stat tmp config
  stat:
    path: /tmp/ansible-config.txt
  register: tmp_config
  changed_when: false

- name: Get cksum of tmp config
  set_fact:
    tmp_sha1: "{{ tmp_config.stat.checksum }}"
  changed_when: false

- name: Drop in final /etc/rancher/rke2/config.yaml
  copy:
    src: /tmp/ansible-config.txt
    remote_src: yes
    dest: /etc/rancher/rke2/config.yaml
    mode: "0640"
    owner: root
    group: root
    backup: yes
  when: not previous_rke2_config.stat.exists or (tmp_sha1 != previous_rke2_config.stat.checksum)

- name: Remove tmp config file
  ansible.builtin.file:
    path: /tmp/ansible-config.txt
    state: absent
  changed_when: false

- name: Restart rke2-server if package installed and config changed
  service:
    state: restarted
    name: rke2-server
  when:
    - ansible_facts.services["rke2-server.service"] is defined
    - "ansible_facts.services['rke2-server.service'].state == 'running'"
    - tmp_sha1 != previous_rke2_config.stat.checksum

- name: Restart rke2-agent if package installed and config changed
  service:
    state: restarted
    name: rke2-agent
  when:
    - ansible_facts.services["rke2-agent.service"] is defined
    - "ansible_facts.services['rke2-agent.service'].state == 'running'"
    - tmp_sha1 != previous_rke2_config.stat.checksum
