---
- name: YUM | Install rke2-server
  yum:
    name: rke2-server
    state: latest  # noqa package-latest

- name: config.yaml | server
  lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: "server: https://{{ server_ip }}:9345"

- name: Add Token to config.yaml
  lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: "token: {{ hostvars['RKE2_TOKEN_HOLDER']['token'] }}"

- name: Add tls-san to first server pt1
  lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: "tls-san:"
  when: tls_san is defined

- name: Add tls-san to first server pt2
  lineinfile:
    path: /etc/rancher/rke2/config.yaml
    insertafter: "tls-san:"
    line: "  - {{ item }}"
  with_items:
    - "{{ tls_san }}"
  when: tls_san is defined

- name: SYSTEMD | rke2-server
  ansible.builtin.systemd:
    name: rke2-server
    state: started
    enabled: yes
