---
- name: YUM-Based | Install rke2-server
  yum:
    name: rke2-server
    state: latest  # noqa package-latest
  when: ansible_os_family == 'RedHat'

- name: TARBALL | Moving Systemd units to /etc/systemd/system
  ansible.builtin.copy:
    src: /usr/local/lib/systemd/system/rke2-server.service
    dest: /etc/systemd/system/rke2-server.service
    mode: '0755'
    owner: root
    group: root
    remote_src: yes
  when: ansible_os_family != 'RedHat'

- name: Add server url to config file
  lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: "server: https://{{ server_ip }}:9345"

- name: Add token to config.yaml
  lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: "token: {{ hostvars['RKE2_TOKEN_HOLDER']['token'] }}"

- name: Add tls-san to first server pt1
  lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: "tls-san:"
  when: tls_san is defined

- name: Add tls-san to first server pt2
  lineinfile:
    path: /etc/rancher/rke2/config.yaml
    insertafter: "tls-san:"
    line: "  - {{ item }}"
  with_items:
    - "{{ tls_san }}"
  when: tls_san is defined

- name: Start rke2-server
  ansible.builtin.systemd:
    name: rke2-server
    state: started
    enabled: yes
