---

## CIS-Mode
# https://docs.rke2.io/security/hardening_guide/
- name: CONFIG | enable CIS-MODE
  lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: "profile: cis-1.5"

# create etcd group
- name: CIS | create etcd group
  group:
    name: etcd
    state: present

# create etcd user
- name: CIS | create etcd user
  user:
    name: etcd
    comment: etcd user
    shell: /bin/nologin
    group: etcd

# # CIS Mode Kernel Hardening
# - name: CIS | copy systemctl file for kernel hardening
#   ansible.builtin.copy:
#     src: /usr/share/rke2/rke2-cis-sysctl.conf
#     dest: /etc/sysctl.d/60-rke2-cis.conf
