---
# Does the /etc/rancher/rke2 directory exist?
- name: Does the /etc/rancher/rke2 directory exist?
  stat:
    path: /etc/rancher/rke2
  register: etc_rancher_rke2

- name: Create the /etc/rancher/rke2 config dir
  ansible.builtin.file:
    path: /etc/rancher/rke2
    state: directory
    recurse: yes
  when: not etc_rancher_rke2.stat.exists

- name: Does /etc/rancher/rke2/config.yaml exist
  stat:
    path: /etc/rancher/rke2/config.yaml
  register: etc_rancher_rke2_config

- name: create the /etc/rancher/rke2/config.yaml file
  ansible.builtin.file:
    path: /etc/rancher/rke2/config.yaml
    state: touch
  when: not etc_rancher_rke2_config.stat.exists

# CONFIG FILE GENERATION
- name: config.yaml | config enable selinux
  lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: "selinux: {{ rke2_selinux }}"
  when: rke2_selinux | bool

- name: config.yaml | config enable selinux
  lineinfile:
    dest: /etc/rancher/rke2/config.yaml
    line: "token: {{ rke2_config_token }}"
  when: rke2_selinux | bool
