---

# This role installs RKE2 on control plane
# nodes and on worker nodes that are
# RHEL/CentOS 7/8 based.
# TODO: Add Ubuntu 18/20 support

- name: Populate service facts
  service_facts:

# Checks if Red Hat system
- name: Currently REQUIRES YUM based system
  meta: end_play
  when: ansible_os_family != 'RedHat'

# Setup Yum repos
- include: yum.yml
  become: yes

# Setup needed directories, touch config files,
# setup selinux, set rke2_write_kubeconfig_mode
- include: config.yml
  become: yes

# Disable Firewalld
# We recommend disabling firewalld. For Kubernetes 1.19, firewalld must be turned off.
- name: disable FIREWALLD
  ansible.builtin.systemd:
    name: firewalld
    state: stopped
    enabled: no
  become: yes
  when: ansible_facts.services["firewalld.service"] is defined

# CIS mode
- import_tasks: cis-profile.yml
  when: rke2_cis_mode
